### ISSUE TITLE
How to avoid blank screen when user has JS disabled

### ISSUE THREAD

**Issue by dshomoye** [mciastek/sal#38]
So I'm using this on a site and its been working perfectly well. I decided to see what would break on the site when the user has js disabled, ideally _most_ things would work since it's just a static site but everything element with `data-sal` is not displayed (but are still in the DOM after checking devtools).
It's a gatsby site and I'm using the [gatsby-plugin-scroll-reveal](https://www.gatsbyjs.org/packages/gatsby-plugin-scroll-reveal/) which calls this library. Just wanted to know how you would recommend getting around this.

**Comment by mciastek** [comment]
I think that adding a disabled state class (`disabledClassName` in [options](https://github.com/mciastek/sal#options)) to body would do the job. In this case, you should add `sal-disabled` to `class` attribute of body. This class reverts all CSS styles applied to animated elements. By default, when sal is launched, it removes this `disabledClassName` from body element. For disabled JS, elements are visible, because body has `disabledClassName` attached. For enabled JS, elements are hidden and then animated, because sal removes `disabledClassName` from body on init. Let me know if this makes sense to you.

**Comment by dshomoye** [comment]
Thanks for the reply! Definitely makes sense 👍.
I just tried it out and it works perfectly.
For anyone curious, I had to do something like this in `gatsby-ssr.js`
```js
exports.onRenderBody = ({ setBodyAttributes }) => {
  setBodyAttributes({
    className: "sal-disabled"
  })
}
```
