### ISSUE TITLE
Threshold vs height

### ISSUE THREAD

**Issue by florianbouvot** [mciastek/sal#42]
Hi, I want animate large area (height), I try different pourcentage value for threshold but result are not good.  

Is it possible to use a fixed value for `threshold` like `threshold: '100px' or is there any others way to fix that?

Thank you, Florian.

**Comment by mciastek** [comment]
According to IntersectionObserver [docs](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/IntersectionObserver#Parameters), threshold can be only a number or an array of numbers. Currently, sal.js doesn't support array of numbers. If you could create a demo with this particular issue, maybe I could help.

**Comment by florianbouvot** [comment]
Thank you for your feedback, I try to create a demo of my issue.

**Comment by florianbouvot** [comment]
@mciastek I can't create a demo but this is a real project with the issue : https://www.caveduvaldor.com

Open this link on a small devices view and look at the third section of the page, user think there is no content.
If we can set something like `100px` it will always works but percentage value is an issue if the animated area is very height.

**Comment by mciastek** [comment]
The `threshold` doesn't accept absolute values, only relative ones - it's mentioned in [docs](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Intersection_observer_options). It's not possible to pass `100px`. You can use only floats or integers here. I can suggest to apply a custom animation to this tall section. The issue here is translate value, which by default is set to [20% of the height](https://github.com/mciastek/sal/blob/master/src/sal.scss#L7). You can add you custom animation, that will use translate with fixed value, like `100px`. Then this section will be shifted down by `100px` and user will need to scroll only 100px to see animation. Let me know if it helps you.

**Comment by florianbouvot** [comment]
@mciastek thank you, I'll try to use a fixed offset ;)

**Comment by mciastek** [comment]
Sure, I'm closing this PR. Reopen when needed.
