### ISSUE TITLE
Suggestion: fail without throwing an error

### ISSUE THREAD

**Issue by ictbeheer** [mciastek/sal#44]
Currently when IntersectionObservers is not available, sal disables the animations gracefully but throws an Error afterwards.

This causes it to show up in Sentry, but more importantly, when it is bundled with other scripts (in my case by WP Rocket) all other scripts in the same file are not executed anymore.

Would you consider adding an option to disable the error and just let sal.js exit silently?

**Comment by mciastek** [comment]
I'd like to not add such option, because throwing such error tells developer that Intersection Observer is not loaded. If you want to silence this error, you can catch it with try/catch, e.g.:

```js
try {
  sal();
} catch(error) {
  // do something with you error, i.e. console.error(error)
}
```

Using try/catch Sentry won't get this error and it will not stop the execution of other scripts.

Let me know if it helps you.

**Comment by ictbeheer** [comment]
Thanks for your response, using the try/catch indeed does the trick.
